AUTO_SHIFT_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
OLED_ENABLE = yes
SPACE_CADET_ENABLE = yes

CAPS_WORD_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
# Optimization - https://docs.qmk.fm/#/squeezing_avr
LTO_ENABLE = yes